services:
  servicea:
    build:
      context: .
      dockerfile: ServiceA/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - WEBSOCKET_URI=ws://serviceb:5297/ws

  serviceb:
    build:
      context: .
      dockerfile: ServiceB/Dockerfile
    ports:
      - "5001:5297"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5297
